version: '3.7'

services:

  nginx:
    image: nginx:1.15-alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    links:
      - frontend
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot


  frontend:
    image: ${FRONTEND_IMAGE_NAME}
    #ports:
    #  - "8080:80"
    links:
      - backend

  backend:
    image: ${BACKEND_IMAGE_NAME}
    environment:
      REDIS_URL: redis://redis:6379/
    env_file:
      - config.env
      - config.env.local
    links:
      - redis

  workers:
    image: ${BACKEND_IMAGE_NAME}
    command: /app/run-worker.sh
    # command: /app/run-wait.sh
    env_file:
      - config.env
      - config.env.local
    environment:
      REDIS_URL: redis://redis:6379/
      TARGET_AUTH_FILE: /run/secrets/secret.xoauth2.json
    secrets:
      - secret.xoauth2.json
    links:
      - redis
    deploy:
      replicas: 2

  redis:
    image: redis
    #ports:
    #  - "6379:6379"

secrets:
  secret.xoauth2.json:
    file: ./secret.xoauth2.json
